apiVersion: apps/v1
kind: Deployment
metadata:
  name: productservice
spec:
  selector:
    matchLabels:
      app: productservice
  template:
    metadata:
      labels:
        app: productservice
    spec:
      containers:
      - image: demomicroservice.azurecr.io/productservice:latest 
        name: productservice        
        ports:
        - containerPort: 80
          name: productservice