apiVersion: apps/v1
kind: Deployment
metadata:
  name: commservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: commservice
  template:
    metadata:
      labels:
        app: commservice
    spec:
      containers:
      - image: nikkuaryan/commservice:latest 
        name: commservice

---

apiVersion: v1
kind: Service
metadata:
  name: communicationservice-clusterip-serv
spec:
  selector:
    app: commservice
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
